apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: eu.gcr.io/tutorial-243616/server:tsp4
        ports:
        - containerPort: 3000
          name: http
        imagePullPolicy: Always
---
kind: Service             
apiVersion: v1            
metadata:                 
  name: server-service     
spec:
  selector:
    app: server
  ports:
  - protocol: TCP 
    targetPort: 3000 
    port: 3000
  type: ClusterIP 
